import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#abd600",
        "surface-dim": "#131313",
        "secondary-container": "#474746",
        "inverse-surface": "#e2e2e2",
        "text-muted": "#888888",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#474747",
        "on-secondary-fixed": "#1b1b1c",
        "background": "#131313",
        "outline-variant": "#444933",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-primary": "#283500",
        "on-primary-fixed": "#161e00",
        "on-surface": "#e2e2e2",
        "surface-container": "#1f1f1f",
        "surface-bright": "#393939",
        "on-primary-fixed-variant": "#3c4d00",
        "inverse-primary": "#506600",
        "border-muted": "#333333",
        "surface-tint": "#abd600",
        "surface-variant": "#353535",
        "on-tertiary": "#303030",
        "inverse-on-surface": "#303030",
        "secondary-fixed": "#e5e2e1",
        "on-error": "#690005",
        "outline": "#8e9379",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e2e2e2",
        "terminal-lime": "#ccff00",
        "surface-container-low": "#1b1b1b",
        "on-surface-variant": "#c4c9ac",
        "primary-fixed": "#c3f400",
        "on-secondary-container": "#b7b5b4",
        "secondary": "#c8c6c5",
        "surface-container-highest": "#353535",
        "on-secondary": "#303030",
        "text-body": "#e5e7eb",
        "surface-slate": "#1e1e1e",
        "on-tertiary-container": "#656464",
        "surface": "#131313",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-container": "#556d00",
        "tertiary": "#ffffff",
        "tertiary-fixed": "#e4e2e1",
        "primary": "#ffffff",
        "error-container": "#93000a",
        "primary-container": "#c3f400",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474746",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#e4e2e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "48px",
        "sidebar-width": "280px",
        "container-padding": "24px",
        "grid-unit": "40px",
      },
      fontFamily: {
        "title-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "code-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
        "display-lg": ["var(--font-jetbrains-mono)", "monospace"],
        "display-lg-mobile": ["var(--font-jetbrains-mono)", "monospace"],
        "body-base": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-md": ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "title-sm": ["18px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "700" }],
        "code-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.2em", fontWeight: "500" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "800" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-base": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
